name: cursoNode.com CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v3

    - name: Deploy para meu hosting
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        SCRIPTS: |
          pwd
          cd ./app
          npm install
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
